version: "3.1"

services:
  mysqlsrv:
    image: mysql:8.0.13
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql/
volumes:
  database: