CREATE TABLE TB_PET (
	ID  BINARY(16) NOT NULL PRIMARY KEY,
	NAME VARCHAR(40) NOT NULL COMMENT 'PET NAME',
	SPECIES VARCHAR(40) NOT NULL COMMENT 'PET SPECIE',
	BREED VARCHAR(40) NOT NULL COMMENT 'PET BREED',
	SEX CHAR(1) NOT NULL COMMENT 'F (FEMALE) OR M (MALE)',
	AGE TINYINT,
	WEIGHT FLOAT,
	SIZE CHAR(1) COMMENT 'S (SMALL), M (MEDIUM) OR L (LARGE)',
	COLOR VARCHAR(40) COMMENT 'PET COLOR',
	NEUTERED CHAR(1) COMMENT 'Y (YES) OR N (NO)',
	ORIGIN  CHAR(1)  COMMENT 'SURRENDER (S) OR RESCUED (R)',
	SITUATION CHAR(1) COMMENT 'A (ADOPTED), D (DECEASED) OR S (SHELTERED)',
	REGISTERED_AT DATETIME NOT NULL
);
    
CREATE TABLE TB_VACCINE (
	ID_VACCINE  BINARY(16) NOT NULL PRIMARY KEY,
	NAME_VACCINE VARCHAR(40) NOT NULL COMMENT 'VACCINE NAME',
	SPECIES CHAR(1) COMMENT 'D (DOG), C (CAT) OR B (BOTH)',
	QT_DOSES INT COMMENT 'QUANTITY VACCINE DOSES',
	INTERVAL_DOSE INT COMMENT 'INTERVAL DOSES IN WEEKS'
);
    
CREATE TABLE TB_PET_VACCINE (
	ID_PET_VACCINE BINARY(16) NOT NULL PRIMARY KEY,
  	ID_PET BINARY(16) NOT NULL,
	ID_VACCINE BINARY(16) NOT NULL,
	DOSE_NUMBER VARCHAR(40) NOT NULL COMMENT 'DOSE NUMBER',
	FOREIGN KEY (ID_PET) REFERENCES TB_PET(ID),
  	FOREIGN KEY (ID_VACCINE) REFERENCES TB_VACCINE(ID_VACCINE)
);

-- SPECIAL THANKS TO MY GIRLFRIEND TO BUILD THIS SCHEMA!